name: release

on:
  push:
    branches:
      - 'master'
      - 'beta'
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (No "v")'
        required: true
        type: string
  pull_request:
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      -
        name: Setup TinyGo
        run: |
          wget https://github.com/tinygo-org/tinygo/releases/download/v0.27.0/tinygo_0.27.0_amd64.deb
          sudo dpkg -i tinygo_0.27.0_amd64.deb
      -
        name: Release
        if: success() && startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPQ_KEY: ${{ secrets.OPQKEY }}
        run: |
          go mod tidy
          go run .
